# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCU9iem2h3jLemrXm7vHGA7T4OsOVxtG
"""

import pandas as pd

def transform(data):
    """
    Hàm xử lý và chuẩn hóa dữ liệu giao thông
    Args:
        data (pd.DataFrame): Dữ liệu thô từ DataFrame
    Returns:
        pd.DataFrame: Dữ liệu đã chuẩn hóa
    """
    try:
        # 1. Tạo cột `date_time` từ `date` và `time`
        data['date_time'] = pd.to_datetime(
            data['date'].astype(str) + ' ' + data['time'].astype(str),
            errors='coerce'
        )

        # 2. Xử lý dữ liệu thiếu hoặc không hợp lệ
        # Loại bỏ các dòng thiếu thông tin chính
        data = data.dropna(subset=['date_time', 'location', 'type'])

        # Xử lý cột 'damage': chuyển về số nguyên, thay giá trị lỗi bằng 0
        data['damage'] = pd.to_numeric(data['damage'], errors='coerce').fillna(0).astype(int)

        # 3. Chuẩn hóa nội dung văn bản
        data['location'] = data['location'].str.strip().str.title()  # Loại bỏ khoảng trắng và viết hoa chữ đầu
        data['type'] = data['type'].str.strip().str.lower()          # Chuyển tất cả sang chữ thường

        # 4. Chọn các cột cần thiết
        data_cleaned = data[['date_time', 'location', 'type', 'damage']]

        print("Dữ liệu đã được chuẩn hóa thành công!")
        return data_cleaned

    except Exception as e:
        print(f"Lỗi trong quá trình Transform: {e}")
        return None

# Ví dụ sử dụng
if __name__ == "__main__":
    # Dữ liệu mẫu
    raw_data = {
        'date': ['2024-12-01', '2024-12-01', '2024-12-02', None],
        'time': ['14:30', '16:00', '09:00', '20:15'],
        'location': [' District 1, HCMC ', 'District 3, HCMC', None, 'District 2, HCMC'],
        'type': ['Collision ', ' Serious Accident', 'collision', ' Minor Accident '],
        'damage': ['2', '5', None, '0']
    }

    # Tạo DataFrame từ dữ liệu mẫu
    df = pd.DataFrame(raw_data)

    # Chạy hàm Transform
    cleaned_data = transform(df)

    # Hiển thị dữ liệu đã xử lý
    if cleaned_data is not None:
        print(cleaned_data)